### ISSUE TITLE
Consider switching from mkdocs to docusaurus

### ISSUE THREAD

**Issue by jzazo** [microsoft/rats#127]
https://docusaurus.io/

**Comment by ms-lolo** [comment]
what dx improvements are you looking for, specifically? docusaurus seems to be tightly integrated with react which makes me hesitate to use it. at a glance, mkdocs looks like the better experience but we can tackle capability gaps if we use this ticket to describe current limitations you're hitting.

**Comment by ms-lolo** [comment]
i'm closing this one because mkdocs is amazing and it added the features needed to remove sphinx :)
