### ISSUE TITLE
improve service definition dx

### ISSUE THREAD

**Issue by ms-lolo** [microsoft/rats#85]
we had the notation of private and public services.
perhaps we should consider something like

```
@app.service
def my_service_provider_method(self) -> MyService:
    ...
```
for creating a private service, without need to name it.  the decorator can automatically create a service id from module+class+method names.

Within the module we can refer to this service as `@apps.service_id(MyContainer.my_service_provider_method)`, and in particular we can create a public service id using:

```
class ExampleServiceIds:
    MY_SERVICE = @apps.service_id(MyContainer.my_service_provider_method)
```

_Originally posted by @elonp in https://github.com/microsoft/rats/pull/76#discussion_r1548180414_

**Comment by elonp** [comment]
Done in https://github.com/microsoft/rats/pull/111.
Note that this reverses the dependency between the container class and the service ids class.  We should continue the discussion to see if that reversal is OK.
